# Generated by Django 2.2.5 on 2019-09-05 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=18, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
